# Generated by Django 5.1.4 on 2024-12-22 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('numero_parte', models.CharField(max_length=100)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='refacciones/')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refacciones.familia')),
            ],
        ),
    ]
